#!/bin/bash
#SBATCH --mem=20G

module load bioinfo/SweeD/4.0.0

cd /home/knam/work/Nlugens_GBS/Revision/SweeD/res
	
SweeD -name P1.4 -input /home/knam/work/Nlugens_GBS/Revision/SweeD/vcf/P1.4.vcf -grid 10

