#!/bin/bash
#SBATCH --mem=20G

module load bioinfo/SweeD/4.0.0

cd /home/knam/work/Nlugens_GBS/Revision/SweeD/res
	
SweeD -name P2.13 -input /home/knam/work/Nlugens_GBS/Revision/SweeD/vcf/P2.13.vcf -grid 10

